### ISSUE TITLE
[BUG] - Client crash and unregistered area

### ISSUE THREAD

**Issue by wolfkidsounds** [viniciusgf2/Ambience#29] opened 2020-09-23 23:11 UTC
**Describe the bug**
When marking an area, the soundnicer tool sometimes does not register correctly and you get the "area name" selection screen twice, after that, the client crashes.

**Where playing in SinglePlayer or Multiplayer?**
-Multiplayer

**To Reproduce**
1. create areaname and select sound in config
2. go in multiplayer
3. select large area (100x10 blocks or something)
4. right click again inside the selection to get the sound selection box (area naming selection)
5. click confirm.
6. right click again and the same dialog appears
7. click confirm -> game crashes

**Expected behavior**
After clicking on "confirm" the selected area is registered and the other UI (where you can select if you want to see the borders and such) appears.

**Screenshots**
none

**Mods used or modpack (please complete the following information):**
[modlist.txt](https://github.com/viniciusgf2/Ambience/files/5272460/modlist.txt)

**Mod Version used:
Ambience-1.12.2-1.6.1

**Please send the followings files to help track the issue:
[ambience.properties.txt](https://github.com/viniciusgf2/Ambience/files/5272466/ambience.properties.txt)
*actual file is not in .txt only for uploading on github*
*\crash-reports\crash-(last date)-server* only client crashes
[crash-2020-09-24_01.00.06-client.txt](https://github.com/viniciusgf2/Ambience/files/5272461/crash-2020-09-24_01.00.06-client.txt)

**Additional context**
I also had this issue with smaller areas. Maybe it takes a little for registering and I am too fast?

*Keep it up! <3*

**Comment by wolfkidsounds** [comment] 2020-09-23 23:12
ADD:

After login, all is fine, the area is registered and works flawlessly...

**Comment by viniciusgf2** [comment] 2020-09-25 02:13
when you create a area do you imediately right click again to reopen the window? because it takes a few seconds for the server effectly register the area, as when you create the area it creates a schedule task on the server to it create when finishes the currently running tasks

**Comment by wolfkidsounds** [comment] 2020-09-25 13:32
I don't immediately right click but on large areas (like this) it probably took around 15-20 seconds. Maybe one could add a timer or something that prevents right clicking during that period? (for example "please wait while the area is being registered")? :)

**Comment by viniciusgf2** [comment] 2020-09-27 15:30
it's takes time to create the areas but not that time 15-20, it takes like 1-3 seconds or less it's depends on the server TPS, I could not reproduce this error in my game

**Comment by viniciusgf2** [comment] 2020-12-01 15:15
I'm closing as I couldn't reproduce it and this probably is a very sporadic bug to occur

**Closed by viniciusgf2** 2020-12-01 15:15 UTC
