### ISSUE TITLE
Song Switcher Crash

### ISSUE THREAD

**Issue by TheRealZonko** [viniciusgf2/Ambience#19] opened 2020-09-07 14:56 UTC
This happened in my singleplayer world.

Time: 2020-09-07 11:00:15 PDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at vaskii.ambience.objects.blocks.SongSwitcher.onBlockActivated(SongSwitcher.java:319)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more

**Comment by viniciusgf2** [comment] 2020-09-07 16:38
I've tried to make it crash here in my game by right clicking, turning on/off redstone, etc... but I couldn't reproduce the bug, what did you made exactly for this to crash, and on which version? 1.12 or 1.15?

**Comment by viniciusgf2** [comment] 2020-10-02 14:43
I'm closing it, as it appears to be working and I couldn't reproduce the bug in my side

**Closed by viniciusgf2** 2020-10-02 14:43 UTC
